INSERT INTO ROL (ROL_NOMBRE) values('ROLE_USER');
INSERT INTO ROL (ROL_NOMBRE) values('ROLE_ADMIN');

INSERT INTO USUARIO (NOMBRE, NOMBRE_USUARIO, EMAIL, PASSWORD) VALUES ('Giovanna Caceres', 'giovanna', 'giovanna@gmail.com', '$2a$10$ZvJlySiFyu/L2xXMEOHSBuC2sQEQXuggfQx/LI19lB3X.X6Cr4b3G');

INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES ( 1, 2 );